# Generated by Django 4.2.9 on 2025-07-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Casino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("website_url", models.URLField()),
                ("logo", models.ImageField(upload_to="logos/")),
                ("license_type", models.CharField(max_length=100)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("min_deposit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payout_speed", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", models.TextField()),
                ("meta_title", models.CharField(max_length=255)),
                ("meta_description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Slots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("rtp", models.DecimalField(decimal_places=2, max_digits=4)),
                ("volatility", models.CharField(max_length=100)),
                ("demo_url", models.URLField()),
                ("image", models.ImageField(upload_to="slots/")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("rating", models.IntegerField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "casino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.casino",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CasinoSlots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "casino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.casino"
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.slots"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("no_deposit", "No Deposit"),
                            ("deposit", "Deposit Bonus"),
                            ("cashback", "Cashback"),
                            ("freespins", "Free Spins"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.CharField(max_length=100)),
                ("wagering", models.CharField(max_length=100)),
                ("bonus_code", models.CharField(blank=True, max_length=100, null=True)),
                ("terms_url", models.URLField(blank=True, null=True)),
                ("is_exclusive", models.BooleanField(default=False)),
                (
                    "casino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="core.casino",
                    ),
                ),
            ],
        ),
    ]
