# Generated by Django 4.2.9 on 2025-07-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonus",
            name="amount_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bonus",
            name="amount_nb",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bonus",
            name="wagering_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bonus",
            name="wagering_nb",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="description_nb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="name_nb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="content_nb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="meta_description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="meta_description_nb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="meta_title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="meta_title_nb",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="slug_en",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="slug_nb",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guide",
            name="title_nb",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
