# Generated by Django 4.2.9 on 2025-07-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_bonus_amount_en_bonus_amount_nb_bonus_wagering_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guide",
            name="slug_en",
        ),
        migrations.RemoveField(
            model_name="guide",
            name="slug_nb",
        ),
        migrations.AddField(
            model_name="casino",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="meta_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="meta_description_nb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="casino",
            name="meta_title_nb",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="slots",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slots",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="slots",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="guide",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guide",
            name="meta_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guide",
            name="meta_description_nb",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guide",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="guide",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="guide",
            name="meta_title_nb",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
