# Generated by Django 4.2.9 on 2025-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_guide_slug_en_remove_guide_slug_nb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casino",
            name="bonus_amount",
            field=models.PositiveIntegerField(default=0, help_text="NOK or EUR"),
        ),
        migrations.AddField(
            model_name="casino",
            name="bonus_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="casino",
            name="freespins",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="casino",
            name="wager",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
