# Generated by Django 4.2.9 on 2025-07-11 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_casinoreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casinoreview",
            options={},
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
