# Generated by Django 4.2.9 on 2025-07-11 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_casinoreview_options_delete_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bonus",
            options={"verbose_name": "Bonus", "verbose_name_plural": "Bonuses"},
        ),
        migrations.AlterModelOptions(
            name="casinoslots",
            options={
                "verbose_name": "Casino slot",
                "verbose_name_plural": "Casino slots",
            },
        ),
        migrations.AlterModelOptions(
            name="slots",
            options={"verbose_name": "Slot", "verbose_name_plural": "Slots"},
        ),
    ]
