# Generated by Django 4.2.9 on 2025-07-11 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_bonus_options_alter_casinoslots_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casinoreview",
            name="slug",
        ),
    ]
