# Generated by Django 4.2.9 on 2025-07-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_casinoreview_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casino",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
