# Generated by Django 4.2.9 on 2025-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_casino_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "method_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="casino",
            name="deposit_methods",
            field=models.ManyToManyField(
                blank=True, related_name="casino_deposit", to="core.paymentmethod"
            ),
        ),
        migrations.AddField(
            model_name="casino",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.tag"),
        ),
        migrations.AddField(
            model_name="casino",
            name="withdrawal_methods",
            field=models.ManyToManyField(
                blank=True, related_name="casino_withdrawal", to="core.paymentmethod"
            ),
        ),
    ]
