# Generated by Django 4.2.9 on 2025-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_casino_deposit_methods_remove_casino_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casino",
            name="deposit_methods",
            field=models.ManyToManyField(
                blank=True, related_name="casinos_deposit", to="core.paymentmethod"
            ),
        ),
        migrations.AddField(
            model_name="casino",
            name="withdrawal_methods",
            field=models.ManyToManyField(
                blank=True, related_name="casinos_withdrawal", to="core.paymentmethod"
            ),
        ),
    ]
