# Generated by Django 4.2.9 on 2025-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_casino_deposit_methods_casino_withdrawal_methods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casinotag",
            name="casino",
        ),
        migrations.RemoveField(
            model_name="casinotag",
            name="tag",
        ),
        migrations.AddField(
            model_name="casino",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.tag"),
        ),
        migrations.AlterField(
            model_name="casino",
            name="deposit_methods",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"method_type": "deposit"},
                related_name="casinos_with_deposit",
                to="core.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="casino",
            name="withdrawal_methods",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"method_type": "withdrawal"},
                related_name="casinos_with_withdrawal",
                to="core.paymentmethod",
            ),
        ),
        migrations.DeleteModel(
            name="CasinoPaymentMethod",
        ),
        migrations.DeleteModel(
            name="CasinoTag",
        ),
    ]
