# Generated by Django 4.2.9 on 2025-07-11 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_casinotag_casino_remove_casinotag_tag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casino",
            name="bonus_amount",
        ),
        migrations.RemoveField(
            model_name="casino",
            name="bonus_percent",
        ),
        migrations.RemoveField(
            model_name="casino",
            name="freespins",
        ),
        migrations.RemoveField(
            model_name="casino",
            name="wager",
        ),
    ]
