# Generated by Django 4.2.9 on 2025-07-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_casino_bonus_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bonus",
            options={},
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="amount_en",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="amount_nb",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="bonus_code",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="bonus_type",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="is_exclusive",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="terms_url",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="wagering",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="wagering_en",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="wagering_nb",
        ),
        migrations.AddField(
            model_name="bonus",
            name="type",
            field=models.CharField(
                choices=[
                    ("freespins", "Free Spins"),
                    ("wager", "Wager"),
                    ("percent", "Bonus Percent"),
                    ("amount", "Bonus Amount"),
                ],
                default="freespins",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bonus",
            name="value",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bonus",
            name="casino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.casino"
            ),
        ),
    ]
